name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - v5

jobs:
  deploy-site:
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/checkout@v2
      - run: pnpm install
      - run: pnpm build
      - run: |
          cd ./packages/site
          pnpm run build
      - run: cp ./CNAME ./dist/CNAME
      - run: |
          cd ./dist
          git init
          git config --local user.name Child-qjj
          git config --local user.email 429814031@qq.com
          git add .
          git commit -m "update by release action"
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{secrets.PERSONAL_ACCESS_TOKEN}}
          directory: ./dist
          branch: gh-pages
          force: true
