name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: true

      - name: Build docs
        run: pnpm docs:build

      - name: Copy CNAME
        run: cp ./CNAME ./docs-dist/CNAME

      - name: Create archive
        run: tar -czf docs-dist.tar.gz -C ./docs-dist .

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: docs-dist
          path: docs-dist.tar.gz
          retention-days: 1

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: docs-dist
          path: ./

      - name: Extract archive
        run: |
          mkdir -p ./docs-dist
          tar -xzf docs-dist.tar.gz -C ./docs-dist

      - name: Setup Git
        run: |
          cd ./docs-dist
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Deploy docs - ${{ github.sha }}"

      - name: Push to gh-pages
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{  secrets.PERSONAL_ACCESS_TOKEN }}
          directory: ./docs-dist
          branch: gh-pages
          force: true
