name: CI

on:
  push:
    branches: [ main, develop, 'v*' ]
  pull_request:
    branches: [ main, develop, 'v*' ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm and dependencies
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: true

      - name: CI
        run: pnpm run ci

  coverage:
    name: Coverage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm and dependencies
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: true

      - name: Test with coverage
        run: pnpm run test:cov

      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v3
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
